[build]
builder = "NIXPACKS"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs", "playwright", "chromium"]

[build.nixpacksPlan.phases.install]
cmds = ["npm install", "npx playwright install --with-deps chromium"]

[build.nixpacksPlan.phases.build]
cmds = ["echo 'No build step needed for Express server'"]

[deploy]
startCommand = "node scrape-server.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = "0"
